version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "02:00"
  open-pull-requests-limit: 15
  ignore:
  - dependency-name: webpack
    versions:
    - 5.11.1
