name: Format

on: pull_request

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - uses: actions/setup-node@v6.4.0
      with:
        node-version: 24

    - name: Install testing dependencies
      run: npm install

    - name: Run prettier
      run: npm run format

    - uses: stefanzweifel/git-auto-commit-action@v7.1.0
      with:
        commit_message: Apply prettier changes
        branch: ${{ github.head_ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
