name: Format

on: pull_request

jobs:
  biome:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7

    - uses: actions/setup-node@v6.4.0
      with:
        node-version: 24

    - name: Install dependencies
      run: npm install

    - name: Run Biome
      run: npm run format

    - uses: stefanzweifel/git-auto-commit-action@v7.2.0
      with:
        commit_message: Apply Biome formatting
        branch: ${{ github.head_ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
