name: tests

on: push

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 19.x]

    name: Node ${{ matrix.node-version }}

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v3.8.1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install testing dependencies
      run: yarn install

    - name: Run Tests
      run: yarn test

