name: tests

on: push

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 19.x]

    name: Node ${{ matrix.node-version }}

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v1.4.4
      with:
        node-version: ${{ matrix.node-version }}

    - uses: bahmutov/npm-install@v1

    - name: Run Tests
      run: yarn test

