name: tests

on: push

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    name: Node ${{ matrix.node-version }}

    steps:
    - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1.4.4
        with:
          node-version: ${{ matrix.node-version }}

    - name: Install testing dependencies
      run: yarn install

    - name: Run Tests
      run: yarn test

